package jdbc.exporter;

import java.io.IOException;
import java.nio.file.OpenOption;
import java.nio.file.Path;
import java.util.List;

/**
 * Interface that describes how the exporter used in order to save on a file with different formats and options the QueryResults works.
 * There is a different implementation for any different <code>ExportingFormat</code> type but the <code>ExportingOptions</code> options
 * choosen by the user must be implemented by the system that uses the methods below.
 * 
 * @author andreaconti
 */

public interface QueryExporter {
	
	/**
	 * Writes a description of a table, it must be used before the writeAttributes or when the elements of a table are finished 
	 * because if it is used after the <code>writeAttributes</code> the exporter
	 * will infer that the previously table writing is closed and will reset the attributes memory of the last table.
	 * 
	 * @param string the description of the table
	 * @throws IOException if an I/O error occurs
	 */
	public void writeDescription(String string) throws IOException;
	
	/**
	 * Writes a title for a table, it must be used before the writeAttributes or when the elements of a table are finished 
	 * because if it is used after the <code>writeAttributes</code> the exporter
	 * will infer that the previously table writing is closed and will reset the attributes memory of the last table.
	 * 
	 * @param string the description of the table
	 * @throws IOException if an I/O error occurs
	 */
	public void writeQueryTitle(String title) throws IOException;
	
	/**
	 * Writes and save a list of the current table attributes (column headers), the method <code>writeTuple</code> throws 
	 * 
	 * @param attributes
	 * @throws IOException
	 */
	public void writeAttributes(List<String> attributes) throws IOException;
	
	/**
	 * 
	 * @param attributes
	 * @param lenghtAttributes
	 * @throws IOException
	 */
	public void writeAttributes(List<String> attributes, List<Integer> lenghtAttributes) throws IOException;
	
	/**
	 * 
	 * @param tuple
	 * @throws IOException
	 */
	public void writeTuple(List<String> tuple) throws IOException;
	
	/**
	 * 
	 * @param tuples
	 * @throws IOException
	 */
	public void writeTuples(List<List<String>> tuples) throws IOException;
	
	/**
	 * 
	 * @param filePath
	 * @param fileName
	 * @param options
	 * @throws IOException
	 */
	public void openStream(Path filePath, String fileName, OpenOption... options) throws IOException;
	
	/**
	 * 
	 * @throws IOException
	 */
	public void closeStream() throws IOException;
	
	/**
	 * @return the complete path generated by the exporter
	 */
	public Path getCompletePath();
	
	/**
	 * 
	 * @param format
	 * @return
	 */
	public static QueryExporter getExporter(ExportingFormat format) {
		
		if (format.equals(ExportingFormat.TXT))
			return new TxtQueryExporter();
		else
			throw new ExportingException("FormatExporter for type" + format.getFormat() + "not found");
		
	}

}
